runtime: python39
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)(?!html)$
  static_files: www/\1
  upload: www/.*$

- url: /(.*)$
  static_files: www/\1\.html
  upload: www/.*\.html$
