# Documentation: https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=python
runtime: python310
error_handlers:
- file: 404.html

handlers:
# serve index
- url: /
  secure: optional
  static_files: www/pages/index.html
  upload: www/pages/index.html
# serve the stylesheets
- url: /(.*\.css)
  secure: optional
  static_files: www/\1
  upload: www/(.*\.css)
# serve the javascript
- url: /(.*\.js)
  secure: optional
  static_files: www/\1
  upload: www/(.*\.js)
# serve the asset files
- url: /(.*\.ico)
  secure: optional
  static_files: www/\1
  upload: www/(.*\.ico)
- url: /(.*\.png|.*\.jpg|.*\.jpeg|.*\.gif|.*\.xml|.*\.svg)
  secure: optional
  static_files: www/\1
  upload: www/(.*\.png|.*\.jpg|.*\.jpeg|.*\.gif|.*\.xml|.*\.svg)
# serve font files
- url: /(.*\.ttf)
  secure: optional
  static_files: www/\1
  upload: www/(.*\.ttf)
# serve html files
- url: /pay
  secure: optional
  static_files: www/pages/pay.html
  upload: www/pages/pay.html

- url: /(.*)
  secure: optional
  static_files: www/pages/404.html
  upload: www/pages/404.html