runtime: python39
handlers:

# serve index
# - url: /
#   static_files: www/index.html
#   upload: www/index.html

# serve card page while index is under development
- url: /
  static_files: www/pages/card.html
  upload: www/pages/card.html

# serve the stylesheets
- url: /(.*\.css)
  static_files: www/\1
  upload: www/(.*\.css)
# serve the javascript
- url: /(.*\.js)
  static_files: www/\1
  upload: www/(.*\.js)
# serve the asset files
- url: /(.*\.ico)
  static_files: www/\1
  upload: www/(.*\.ico)
- url: /(.*\.png|.*\.jpg|.*\.jpeg|.*\.gif|.*\.xml|.*\.svg)
  static_files: www/\1
  upload: www/(.*\.png|.*\.jpg|.*\.jpeg|.*\.gif|.*\.xml|.*\.svg)
# serve font files
- url: /(.*\.ttf)
  static_files: www/\1
  upload: www/(.*\.ttf)
# serve anything else as an html file
- url: /(.*)
  static_files: www/pages/\1.html
  upload: www/pages/(.*)\.html