runtime: python39
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /nav\.html
  static_files: www/nav.html
  upload: www/nav.html

- url: /(.*)\.html$
  static_files: www/\1
  upload: www/.*\.html$

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
