runtime: python39
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

# handler for specifically requested .html files, removes the .html extension
- url: /(.*\.html)$
  static_files: www/\1
  upload: www/pages/.*\.html$

# tell gcp to serve the static files
- url: /(~.*)$
  static_dir: \1