steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
- name: "bash"
  script: |
    #!/bin/bash
    versions=$(gcloud app versions list \
      --service default \
      --sort-by '~VERSION.ID' \
      --format 'value(VERSION.ID)' | sed 1,5d)
    for version in $versions; do
      gcloud app versions delete "$version" \
        --service default \
        --quiet
    done
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1600s"