# This is a simple workflow to build this Django project and deploy it as a Google App Engine application 
name: Deploy App Engine

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: GOOGLE_CREDENTIALS

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -   uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: 'personal-webpage-347321@appspot.gserviceaccount.com'

      # Deploy application on Google App Engine
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
